language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install braintree coveralls mock mysqlclient
services:
  - postgresql
env:
  - DB=postgres
before_script:
  - psql -c 'CREATE DATABASE django_medium;' -U postgres
script:
  - python manage.py makemigrations
  - python manage.py collectstatic
  - coverage run python manage.py test
after_success: coveralls
cache: pip
