language: python

matrix:
  include:
    - python: 3.6
      sudo: true

services:
  - postgresql

addons:
  postgresql: "9.4"

addons:
  postgresql: "9.4"

env:
  - DJANGO=2.1 DB=postgres

install:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter

before_script:
  - psql -c 'create database django_medium;' -U postgres

script:
  - python manage.py makemigrations
  - python manage.py migrate notifications
  - coverage run manage.py test

after_success:
  - coveralls
  - codeclimate-test-reporter

cache: pip
