language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

cache: pip

services:
  - postgresql

env:
  - DJANGO=2.1 DB=postgres

install:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter

script: 
  - python manage.py test

after_success:
  - coveralls
  - codeclimate-test-reporter
