language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
env:
  - DB=postgres
before_script:
  - psql -c 'CREATE DATABASE django_medium;' -U postgres
script:
  - python manage.py makemigrations
  - python manage.py test
after_success: coveralls
