language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

services:
  - postgresql

env:
  - DJANGO=2.1.2

install:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter

before_script:
  - psql -c "CREATE DATABASE django_medium;" -U postgres
script: 
  - python manage.py test

after_success:
  - coveralls
  - codeclimate-test-reporter

cache: pip
