language: python
python:
- "3.7"
<<<<<<< HEAD
=======
- "2.7"
>>>>>>> 2cdb5059593e8c1683b33959f47214b8badc5d02
cache: pip
services:
- postgresql
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install codeclimate-test-reporter
before_script:
- createdb test_db
script: 
- python manage.py test
after_success:
- coveralls
- codeclimate-test-reporter
